sudo: required
services:
- docker 


jobs:
  include:
  - stage: build docker image
    script: make build
  - state: test
    script: make test
  - deploy:  
    script: make install
    on:
      branch: master

notifications:
  email: false