sudo: required
language: bash
services:
- docker

env:
  global:
  - secure: YM5uGdrASmv6qfSpLIzUNYm26fHveszeZBUHWkdOxdrjFhYEtq8acapUz6xzZKMzkUYHd5dicuyj1qE2GNt++wV1r1DlcEORTvzJJo7p8ml3oayfIE0/a7xFVZgO50Fgbm/OVv+JxfhT7Uu5k+Zy0qDqSo7xNsQwiMjdf/iAkRTzwFeTluRnkE/R3WUSTwTjPfMVGpPa62igI9cMA5SU3Ydmti/0UwcmRSJ8X/8jDKPB2PbH65hU6/AK+pxnvxmFnMRu1bTf/uAGiB9QGRUWA97Q/zRvN0prtnrBZCpInxr2uy4pM5fRzN/RYYv+4TcG60EB+WG0ggLoERiRGGgOpFMjP1X0E49zkDI3DwjeREWebcJyarCHumbRgvrRMmX/X9KnuOZoLsYzC5Ow4Bt1yOVcPKlofbXXdt/Syie1IkMhsjUceq1kiMVYObT13VQXgtR+Fd/5vaO1zzATMaCO83fWyREWj1cB58bv6FxRr6OW97r27ynEkAnqh4X96ulveA5kLxeuZ10BP7qkuPmnupsImoTF8IERjqZVpFMSt27bsInsb7egMMW9B/1hi756YahO65y00OkEy3I94FLWrxwAbJHuz4mUbdRF8j3jWxPA3rrXGBEQeCX3uvG9/r1bxot8mP9fVCIDVehhU0tZXL86BhUNUvdF8OkyI+XcbOU=
  - secure: PF/eiEtnmLK2RvYIIDzWr79zYckHSPln8R4eB/KpHM167FuUiyyeoTbEnnP3EFuDIdRWS6wTjTEZFt1wTtg8z4F43fotTuaFM5XYdUpfHFaVN0I1T8iKqiayTEx4444DHZqzrZBGALi9K3gM6FicJOArv2qVnKxB55UNSA772L8hKhvYPyFLU7KH+u3qZoosvqXuapJNF0eUZ9khqTxqu8OoyeRD3GGEC2M5kS2zqjRBRukG85Wvlg9VRB23sCxAvjlg6XJZuNipLPE5JCbFLaYZ6T9sntwPrS8Q1JElEj7B7CGSLbADAQ9wV2P4nmJ7yGJP8v2z3eDF6wIiaSSvBSlHkL1v5y/RDbVj0R+ZLLvCKBauw1bhP+NGtaJzqhDrN4GzZA4KQQaT/fdamF+IzUC2n8S2l4k6tHBNGdTqdPe1oLnShZD81ArIYCGThbnp/+zZW4Bsw+LPid8/NyLejFVDWB2Ife3ibFYjLj6mGuyfp2n/Q2nWVEdIpCouoSAmwDi4hXxUhDSwUW6FJxZANSjWLlsWqTCOtnIIpEKlJl4OSC8nHJl6GGWfyEb6/eGYrP4hU1fMADjDAmbypG76bZhiOy8rK+1mNTwrA0Xugn5l8/VwdWAXPE0v9HS3OlQvAHrBNI5pNf7c59jlgBQIQ+RUrY2mUuVD5sLjgrWhgaA=

script:
- make build
- make test
deploy:
- provider: script
  script: make deploy
  on:
    branch: master
notifications:
  email: false
