sudo: required
language: bash
services:
- docker

script:
- make build
- make test

deploy:
- provider: script
  script: IS_RELEASE=true make deploy
  on:
    branch: master

- provider: script
  script: make deploy
  on:
    branch: develop

notifications:
  email: false